config/routes.rb
Rails.application.routes.draw do


  get 'users/edit1' => 'users#edit1', as: :user_update1
  get 'users/edit2' => 'users#edit2', as: :user_update2
  get 'users/select' => 'users#select'

  

  get '/' => 'users#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'comments/new'
  post 'comments/create'
  get 'comments/index'
  post 'comments/create', as:"comments"
  get 'rooms/create'
  #get 'rooms/destroy'
  resources :rooms

  post 'rooms/create'

  get 'friends/new'
  get 'friends/create'
  get 'friends/edit1'
  get 'friends/edit2'
  delete 'friends/destroy'
  namespace :admin do
    resources :users
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.htmls

  resources :users
  get 'search' => 'users#search'
  get "users/:id" =>'users#show'



  mount ActionCable.server => '/cable'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :friends
  has_one_attached :image
  validates :userid, presence: {message: "ユーザーID は必ず入力してください"}, uniqueness: {message: "%{value} はすでに使用されています"}

  mount_uploader :image, UserUploader
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def new
  end

  def edit
  end

  def show
  end

  def index
  end
end

app/controllers/users_controller.rb
require 'logger'
class UsersController < ApplicationController
  before_action :set_user #, only: %i[ show edit update destroy ]
  skip_before_action :login_required, {only: [:new, :create]}

  def index
    flag = 0
    @userss = []
    @users = []

    friend1 = Friend.where(user_id:current_user.id)
    friend2 = Friend.where(friend_id:current_user.id)
    friend1.each do |friend_id|
      last_msg_time1 = Comment.where(sender_id:friend_id.friend_id, receiver_id:current_user.id).last
      last_msg_time2 = Comment.where(sender_id:current_user.id, receiver_id:friend_id.friend_id).last
      last_msg_time1 = last_msg_time1.created_at unless last_msg_time1.nil?
      last_msg_time2 = last_msg_time2.created_at unless last_msg_time2.nil?
      if last_msg_time1 != nil && last_msg_time2 != nil
        if last_msg_time1 < last_msg_time2
          last_msg_time1 = last_msg_time2
        end
      elsif last_msg_time1 == nil
        last_msg_time1 = last_msg_time2
      end
      if User.find_by(id:friend_id.friend_id)
        @userss.push([User.find(friend_id.friend_id), last_msg_time1])
      end
    end
    friend2.each do |friend_id|
      last_msg_time1 = Comment.where(sender_id:friend_id.user_id, receiver_id:current_user.id).last
      last_msg_time2 = Comment.where(sender_id:current_user.id, receiver_id:friend_id.user_id).last
      last_msg_time1 = last_msg_time1.created_at unless last_msg_time1.nil?
      last_msg_time2 = last_msg_time2.created_at unless last_msg_time2.nil?
      if last_msg_time1 != nil && last_msg_time2 != nil
        if last_msg_time1 < last_msg_time2
          last_msg_time1 = last_msg_time2
        end
      end

      @userss.each do |user|
        if user[0] == User.find(friend_id.friend_id)
          flag = 1
          if user[1] != nil && user[1] < last_msg_time1
            user[1] = last_msg_time1
          end
        end
      end

      if flag == 0 && User.find_by(id:friend_id.friend_id)
        @userss.push([User.find(friend_id.friend_id), last_msg_time1])
      end
      flag = 0
    end

    @userss = @userss.sort {|a, b| a[1].to_s <=> b[1].to_s}.reverse
    @userss.each do |user|
      @users.push(user[0])
    end
  end

  def show
    if User.find(params[:id]) != nil
      @user = User.find(params[:id])
    else
      @user = nil
    end

    @users = User.all

  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(current_user.id)
  end


  def select
    @user = User.find(current_user.id)
  end

  def search
    @q = User.ransack(params[:q])
    if params[:q] != nil
      @results = @q.result
    else
      @results = User.all.shuffle
    end
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      if @user&.authenticate(user_params[:password])
        session[:user_id] = @user.id
        redirect_to users_path
      end
    else
      unless @user.valid?
        @user.errors.each do |key, value|
          flash.now[:alert] = value
        end
        render :new
      else
        render :new
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json

  #######編集中#######
  def update
    update_num = judge_update(user_edit_pw_params_confirmation[:current_password], user_edit_pw_params_confirmation[:password], user_edit_pw_params_confirmation[:password_confirmation])
    @user = User.find(current_user.id)

    case update_num
    when 111 then
      #現在のPWと一致する（＝本人確認が取れた場合）
      if @user&.authenticate(user_edit_pw_params_confirmation[:current_password])
        #新PWと新PW(確認)が一致する
        if user_edit_pw_params_confirmation[:password] == user_edit_pw_params_confirmation[:password_confirmation]
          #PWありとして更新する
          @user.update(user_edit_pw_params_update)
          flash[:notice] = "パスワードを変更しました"
          redirect_to users_path
        #新PWと新PW(確認)が一致しない
        else
          flash.now[:alert] = "新しいパスワード が一致しません"
          render :edit2
        end
      #現在のPWと一致しない（＝本人確認が取れていない場合）
      else
        flash.now[:alert] = "現在のパスワード が一致しません"
        render :edit2
      end

    when 0 then
      if user_edit_normal_params_confirmation[:flag].to_i == 1
        #名前、ユーザーIDやプロフィール写真といった情報のみを更新する
        @user.update(user_edit_normal_params_update)
        flash[:notice] = "ユーザー情報を更新しました"
        redirect_to users_path
      else
        flash.now[:alert] = "新たなパスワード と 新たなパスワード(確認) を入力してください"
        render :edit2
      end

    when 100 then
      flash.now[:alert] = "新たなパスワード と 新たなパスワード(確認) を入力してください"
      render :edit2

    when 101 then
      flash.now[:alert] = "新たなパスワード を入力してください"
      render :edit2

    when 110 then
      flash.now[:alert] = "新たなパスワード(確認) を入力してください"
      render :edit2

    when 1, 10, 11 then
      flash.now[:alert] = "現在のパスワード を入力してください"
      render :edit2

    else
      render :select
    end
  end



  # DELETE /users/1 or /users/1.json
  def destroy
    reset_session
    @user = User.find(params[:id])
    @user.destroy

    redirect_to login_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      if current_user != nil
        @user = User.find(current_user.id)
      end
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :userid, :password, :password_confirmation, :image, :name_cont, :q)
    end

    def user_edit_normal_params_confirmation
      params.require(:user).permit(:name, :userid, :current_password, :image, :name_cont, :q, :flag)
    end
    def user_edit_normal_params_update
      params.require(:user).permit(:name, :userid, :image, :name_cont, :q)
    end

    def user_edit_pw_params_confirmation
      params.require(:user).permit(:name, :userid, :password, :password_confirmation, :current_password, :image, :name_cont, :q)
    end
    def user_edit_pw_params_update
      params.require(:user).permit(:name, :userid, :password, :password_confirmation, :image, :name_cont, :q)
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_followerlist.html.erb
<div class="" style="float:left">
  <table id="<%= 'follow_list_' + current_user.id.to_s %>">
    <tbody>
      <% @users.each do |friend| %>
        <%
          @current_user = User.find(current_user.id)
          @judge_result = judge_ff(current_user.id, friend.id)
          @follow = (@judge_result - @judge_result % 10) / 10
          @follower = @judge_result % 10

          last_comments = Comment.where(sender_id:current_user.id, receiver_id:friend.id) + Comment.where(sender_id:friend.id, receiver_id:current_user.id)
          @last_comment = (last_comments.sort {|a, b| a[:created_at] <=> b[:created_at]}).last
          if @last_comment != nil
            @last_comment_date = get_comment_date(@last_comment.created_at)
            @last_comment_time = get_comment_time(@last_comment.created_at)

            if @last_comment.expression == 0 || @last_comment.expression == nil
              @last_comment = @last_comment.content
            elsif @last_comment.expression != nil
              title_length = @last_comment.title.length
              @last_comment = "件名" + "【" + @last_comment.title + "】" + @last_comment.long_content[0, 40 - title_length] + "...."
            end
          else
            @last_comment = ""
            @last_comment_date = "'-- / -- / --"
            @last_comment_time = "-- : --"
          end
        %>
        <% if friend.id != current_user.id && @follow != 0 %>

          <% recent_msg_id = "recent1_" + current_user.id.to_s + "_" + friend.id.to_s %>
          <tr class="index_row_1st" id="<%= recent_msg_id %>">
            <td class="ff_image">
              <% if @judge_result == 22 %>
                <%= image_tag "ff#{@judge_result}.png", class:"ff_image" %>
              <% elsif @judge_result == 21 %>
                <%= image_tag "ff#{@judge_result}.png", class:"ff_image" %>
              <% elsif @judge_result == 20 %>
                <%= image_tag "ff#{@judge_result}.png", class:"ff_image" %>
              <% elsif @judge_result == 12 %>
                <%= image_tag "ff#{@judge_result}.png", class:"ff_image" %>
              <% elsif @judge_result == 11 %>
                <%= image_tag "ff#{@judge_result}.png", class:"ff_image" %>
              <% elsif @judge_result == 10 %>
                <%= image_tag "ff#{@judge_result}.png", class:"ff_image" %>
              <% elsif @judge_result == 2 %>
                <%= image_tag "ff0#{@judge_result}.png", class:"ff_image" %>
              <% elsif @judge_result == 1 %>
                <%= image_tag "ff0#{@judge_result}.png", class:"ff_image" %>
              <% elsif @judge_result == 0 %>
                <%= image_tag "ff0#{@judge_result}.png", class:"ff_image" %>
              <% end %>
            </td>


            <td>
                <% if friend.image.url != nil %>
                  <%= image_tag friend.image.url, :class => "index_icons", style:"float:left" %>
                <% else %>
                  <%= image_tag "人物_デフォルト.png", :class => "index_icons", style:"float:left" %>
                <% end %>
            </td>

            <td><%= link_to friend.userid, "users/#{friend.id}", class:"follower_name", style:"float:right" %></td>

            <td>
              <% if @follow == 2 %>
                <div class="followed_link">
                  <%= link_to 'フォロー解除', friends_edit2_path(user_id: current_user.id, friend_id:friend.id), method: :get %>
                </div>
              <% elsif @follow == 1 %>
                <div class="following_link">
                  <%= link_to 'フォロー申請中', friends_edit2_path(user_id: current_user.id, friend_id:friend.id), method: :get %>
                </div>
              <% elsif @judge_result == 2 %>
                <div class="followback_link">
                  <%= link_to "フォローバック", friends_create_path(friend_id:friend.id) %>
                </div>
              <% elsif @judge_result == 1 || @judge_result == 0 %>
                <div class="follow_link">
                  <%= link_to "フォロー申請", friends_create_path(friend_id:friend.id) %>
                </div>
              <% end %>
            </td>

            <% if @judge_result == 22 %>
            <%
              if current_user.id < friend.id
                @user_id1, @user_id2 = current_user.id, friend.id
              else
                @user_id1, @user_id2 = friend.id, current_user.id
              end

              @room = Room.find_by(user_id1:@user_id1, user_id2:@user_id2)
              if @room == nil
            %>

              <td><%= button_to 'ルーム作成', rooms_create_path(user_id1:@user_id1, user_id2:@user_id2), method: :post, class:"roomMake_link" %></td>
            <% else %>
              <td><%= button_to 'ルーム入室', "/rooms/#{@room.id}", method: :get, class:"roomEntry_link" %></td>
            <% end %>
          <% else %>
            <td class="roomEmpty"> </td>
          <% end %>
          </tr>

          <% recent_msg_id = "recent2_" + current_user.id.to_s + "_" + friend.id.to_s %>

          <tr class="index_row_2nd" id="<%= recent_msg_id %>">
            <td align="right"><%= @last_comment_date + " " + @last_comment_time %></td>
            <td colspan="4"><%= @last_comment %></td>
          </tr>
        <% end %>

      <% end %>
    </tbody>
  </table>

</div>

app/views/users/_myprofile_left.html.erb
<div class="" style="float:right">
  <table>
    <tr>
      <td rowspan="2">
        <% if @current_user.image.url != nil %>
          <%= image_tag @current_user.image.url, class:"index_icons" %>
        <% else %>
          <%= image_tag "人物_デフォルト.png", class:"index_icons" %>
        <% end %>
      </td>
      <td class="myprofile_area1"><%= "名前"%></td>
      <td class="myprofile_area2"><big><strong><%= @current_user.name %></strong></big></td>
    </tr>

    <tr>
      <td class="myprofile_area1"><%= "ユーザーID" %></td>
      <td class="myprofile_area2"><big><strong><%= @current_user.userid %></strong></big></td>
    </tr>
  </table>



  <div class="item-list">

    <div>
      <%= button_to 'ユーザー検索', search_path, method: :get, class: 'user_btn search_link' %>
    </div>

    <div>&emsp;</div>

    <div>
      <%= button_to 'ユーザー情報編集', "/users/select", method: :get, class: 'user_btn edit_link' %>
    </div>

    <div>&emsp;</div>

    <div>
      <%= button_to 'ログアウト', logout_path, method: :delete, class: 'user_btn logout_link' %>
    </div>

    <div>&emsp;</div>

    <div>
      <%= button_to 'アカウント削除', @current_user, method: :delete, class: 'user_btn destroy_link', data: { confirm: 'このアカウントは元に戻せません、よろしいですか？' } %>
    </div>

  </div>

</div>

app/views/users/_new_form.html.erb
<%= form_with(model: user) do |form| %>

  <center>
    <table>
      <tbody>
        <tr>
          <td><%= form.label "名前　　　", class:"user_create_label" %></td>
          <td><%= form.text_field :name, class:"user_create_field", id:"user_create_field", placeholder: "名前" %></td>
        </tr>

        <tr>
          <td><%= form.label "ユーザーID　　　", class:"user_create_label" %></td>
          <td><%= form.text_field :userid, class:"user_create_field", placeholder: "ユーザーID" %></td>
        </tr>

        <tr>
          <td><%= form.label "パスワード　　　", class:"user_create_label" %></td>
          <td><%= form.password_field :password, class:"user_create_field", placeholder: "パスワード" %></td>
        </tr>

        <tr>
          <td><%= form.label "パスワード(再確認)　　　", class:"user_create_label" %></td>
          <td><%= form.password_field :password_confirmation, class:"user_create_field", placeholder: "パスワード(再確認)" %></td>
        </tr>
      </tbody>
    </table>
  </center>

  <br><br>

  <center>
    <%= form.submit "新規登録", class:"user_edit_link" %>
  </center>
<% end %>


<script type="text/javascript">
  window.addEventListener('load', function() {
    document.getElementById('user_create_field').focus();
  })
</script>

app/views/users/_show_followerlist.html.erb
<div class="" style="float:left">
  <center><h2>フォローリスト</h2></center>
<% if @user != nil && @user.id != current_user.id %>
  <table>
    <tbody>
      <% @users.each do |friend| %>
        <%
          @current_user = User.find(current_user.id)
          @judge_result = judge_ff(@user.id, friend.id)
          @follow = (@judge_result - @judge_result % 10) / 10
          @follower = @judge_result % 10
        %>
        <% if @user.id != friend.id && @follow == 2 %>
          <tr class="index_row">
            <td class="ff_image">
              <% if @judge_result == 22 %>
                <%= image_tag "ff#{@judge_result}.png", class:"ff_image" %>
              <% elsif @judge_result == 21 %>
                <%= image_tag "ff#{@judge_result}.png", class:"ff_image" %>
              <% elsif @judge_result == 20 %>
                <%= image_tag "ff#{@judge_result}.png", class:"ff_image" %>
              <% elsif @judge_result == 12 %>
                <%= image_tag "ff#{@judge_result}.png", class:"ff_image" %>
              <% elsif @judge_result == 11 %>
                <%= image_tag "ff#{@judge_result}.png", class:"ff_image" %>
              <% elsif @judge_result == 10 %>
                <%= image_tag "ff#{@judge_result}.png", class:"ff_image" %>
              <% elsif @judge_result == 2 %>
                <%= image_tag "ff0#{@judge_result}.png", class:"ff_image" %>
              <% elsif @judge_result == 1 %>
                <%= image_tag "ff0#{@judge_result}.png", class:"ff_image" %>
              <% elsif @judge_result == 0 %>
                <%= image_tag "ff0#{@judge_result}.png", class:"ff_image" %>
              <% end %>
            </td>

            <%
              @current_user = User.find(current_user.id)
              @judge_result = judge_ff(current_user.id, friend.id)
              @follow = (@judge_result - @judge_result % 10) / 10
              @follower = @judge_result % 10
            %>


            <td>
                <% if friend.image.url != nil %>
                  <%= image_tag friend.image.url, :class => "index_icons", style:"float:left" %>
                <% else %>
                  <%= image_tag "人物_デフォルト.png", :class => "index_icons", style:"float:left" %>
                <% end %>
            </td>

            <% if friend.id == current_user.id %>
              <td><%= link_to friend.userid, users_path, class:"follower_name", style:"float:right" %></td>
            <% else %>
              <td><%= link_to friend.userid, friend, class:"follower_name", style:"float:right" %></td>
            <% end %>

            <td>
              <% if friend.id != current_user.id %>
                <% if @follow == 2 %>
                  <div class="followed_link">
                    <%= link_to 'フォロー解除', friends_edit2_path(user_id: current_user.id, friend_id:friend.id), method: :get %>
                  </div>
                <% elsif @follow == 1 %>
                  <div class="following_link">
                    <%= link_to 'フォロー申請中', friends_edit2_path(user_id: current_user.id, friend_id:friend.id), method: :get %>
                  </div>
                <% elsif @judge_result == 2 %>
                  <div class="followback_link">
                    <%= link_to "フォローバック", friends_create_path(friend_id:friend.id) %>
                  </div>
                <% elsif @judge_result == 1 || @judge_result == 0 %>
                  <div class="follow_link">
                    <%= link_to "フォロー申請", friends_create_path(friend_id:friend.id) %>
                  </div>
                <% end %>
              <% else %>
                <div class="roomEmpty"></div>
              <% end %>
            </td>

            <% if @judge_result == 22 %>
            <%
              if current_user.id < friend.id
                @user_id1, @user_id2 = current_user.id, friend.id
              else
                @user_id1, @user_id2 = friend.id, current_user.id
              end

              @room = Room.find_by(user_id1:@user_id1, user_id2:@user_id2)
              if friend.id != current_user.id
                if @room == nil
              %>

                  <td><%= button_to 'ルーム作成', rooms_create_path(user_id1:@user_id1, user_id2:@user_id2), method: :post, class:"roomMake_link" %></td>
                <% else %>
                  <td><%= button_to 'ルーム入室', "/rooms/#{@room.id}", method: :get, class:"roomEntry_link" %></td>
                <% end %>
              <% end %>

          <% else %>
            <td class="roomEmpty"> </td>
          <% end %>
          </tr>
        <% end %>
        <% end %>

    </tbody>
  </table>

<% else %>
  <center><h2>申し訳ありません　このページは表示できません…  </h2></center>
  <center><%= link_to "トップへ戻る", users_path %></center>
<% end %>

</div>

app/views/users/_show_myprofile.html.erb
  <table>
    <tr>
      <td rowspan="2">
        <% if @user.image.url != nil %>
          <%= image_tag @user.image.url, class:"index_icons" %>
        <% else %>
          <%= image_tag "人物_デフォルト.png", class:"index_icons" %>
        <% end %>
      </td>
      <td class="myprofile_area1"><%= "名前"%></td>
      <td class="myprofile_area2"><big><strong><%= @user.name %></strong></big></td>
    </tr>

    <tr>
      <td class="myprofile_area1"><%= "ユーザーID" %></td>
      <td class="myprofile_area2"><big><strong><%= @user.userid %></strong></big></td>
    </tr>
  </table>

app/views/users/edit.html.erb
<h1>ユーザー情報編集</h1>

<% if User.find_by(id:params[:id]) == nil %>
  <p>不正なログインです</p>
<% elsif User.find(current_user.id) == nil %>
  <p>不正なログインです</p>
<% else %>
  <%= render 'edit_form', user: @user %>
<% end %>

app/views/users/edit1.html.erb
<%= form_with(model: @user) do |form| %>

    <center>
      <table>
        <tbody>
          <tr>
            <td class="user_create_label">名前　　　</td>
            <td><%= form.text_field :name, class:"user_create_field", id:"user_create_field", placeholder: "名前" %></td>
          </tr>

          <tr>
            <td class="user_create_label">ユーザーID　　　</td>
            <td><%= form.text_field :userid, class:"user_create_field", placeholder: "ユーザーID" %></td>
          </tr>

          <tr>
            <td class="user_create_label">タグ付け　　　</td>
            <td><%= form.text_area :description, class:"user_create_field", placeholder: "タグ付け" %></td>
          </tr>

          <tr>
            <td class="user_create_label">プロフィール画像   </td>
            <td>
              <center><%= form.label :image, "プロフィール画像を追加", class:"image_input_btn" %></center>
              <%= form.file_field :image, class:"image_form" %>
            </td>
          </tr>
        </tbody>
      </table>

      <%= form.hidden_field :flag, :value=>"1" %>


      <p><%= form.submit "更新する", class:"user_edit_link" %></p>
    </center>
<% end %>



<script type="text/javascript">
  window.addEventListener('load', function() {
    document.getElementById('user_create_field').focus();
  })
</script>

app/views/users/edit2.html.erb
<%= form_with(model: @user) do |form| %>

  <center>
    <table>
      <tbody>

        <tr>
          <td class="user_create_label">現在のパスワード</td>
          <td><%= form.password_field :current_password, class:"user_create_field", id:"user_create_field", placeholder: "現在のパスワード" %></td>
        </tr>

        <tr>
          <td class="user_create_label">パスワード　　　</td>
          <td><%= form.password_field :password, class:"user_create_field", placeholder: "パスワード" %></td>
        </tr>

        <tr>
          <td class="user_create_label">パスワード(再確認)　　　</td>
          <td><%= form.password_field :password_confirmation, class:"user_create_field", placeholder: "パスワード(再確認)" %></td>
        </tr>

        <%= form.hidden_field :flag, :value=>0 %>


      </tbody>
    </table>
  </center>

  <br><br>

  <center>
          <%= form.submit "更新する", class:"user_edit_link" %>
  </center>
<% end %>



<script type="text/javascript">
  window.addEventListener('load', function() {
    document.getElementById('user_create_field').focus();
  })
</script>

app/views/users/index.html.erb
<% @current_user = User.find(current_user.id) %>
<div class="item-list">
  <center>
    <div class="myprofile">
      <%= render '/users/myprofile_left' %>
    </div>
  </center>

  <p>&emsp;</p>

  <center>
    <div class="followerlist">
      <%= render '/users/followerlist' %>
    </div>
  </center>
</div>

app/views/users/new.html.erb
<%= render 'new_form', user: @user %>

app/views/users/search.html.erb
<%= search_form_for @q, url:"search" do |f| %>
    <%= f.search_field :userid_cont %>
    <%= f.submit %>
<% end %>


<%
  if @results == nil
    @results = User.all.shuffle!
  end
%>
<table>
  <tbody>
    <% @results.each do |result| %>
      <% if result.id != current_user.id %>
        <tr class="index_row">
          <%
            @current_user = User.find(current_user.id)
            @judge_result = judge_ff(current_user.id, result.id)
            @follow = (@judge_result - @judge_result % 10) / 10
            @follower = @judge_result % 10
          %>
          <td class="ff_image">
            <% if @judge_result == 22 %>
              <%= image_tag "ff#{@judge_result}.png", class:"ff_image" %>
            <% elsif @judge_result == 21 %>
              <%= image_tag "ff#{@judge_result}.png", class:"ff_image" %>
            <% elsif @judge_result == 20 %>
              <%= image_tag "ff#{@judge_result}.png", class:"ff_image" %>
            <% elsif @judge_result == 12 %>
              <%= image_tag "ff#{@judge_result}.png", class:"ff_image" %>
            <% elsif @judge_result == 11 %>
              <%= image_tag "ff#{@judge_result}.png", class:"ff_image" %>
            <% elsif @judge_result == 10 %>
              <%= image_tag "ff#{@judge_result}.png", class:"ff_image" %>
            <% elsif @judge_result == 2 %>
              <%= image_tag "ff0#{@judge_result}.png", class:"ff_image" %>
            <% elsif @judge_result == 1 %>
              <%= image_tag "ff0#{@judge_result}.png", class:"ff_image" %>
            <% elsif @judge_result == 0 %>
              <%= image_tag "ff0#{@judge_result}.png", class:"ff_image" %>
            <% end %>
          </td>


          <td>
              <% if result.image.url != nil %>
                <%= image_tag result.image.url, :class => "index_icons", style:"float:left" %>
              <% else %>
                <%= image_tag "人物_デフォルト.png", :class => "index_icons", style:"float:left" %>
              <% end %>
          </td>

          <td><%= link_to result.userid, result, class:"follower_name", style:"float:right" %></td>

          <td>
            <% if @follow == 2 %>
              <div class="followed_link">
                <%= link_to 'フォロー解除', friends_edit2_path(user_id: current_user.id, friend_id:result.id), method: :get %>
              </div>
            <% elsif @follow == 1 %>
              <div class="following_link">
                <%= link_to 'フォロー申請中', friends_edit2_path(user_id: current_user.id, friend_id:result.id), method: :get %>
              </div>
            <% elsif @judge_result == 2 %>
              <div class="followback_link">
                <%= link_to "フォローバック", friends_create_path(friend_id:result.id) %>
              </div>
            <% elsif @judge_result == 1 || @judge_result == 0 %>
              <div class="follow_link">
                <%= link_to "フォロー申請", friends_create_path(friend_id:result.id) %>
              </div>
            <% end %>
          </td>

          <% if @judge_result == 22 %>
          <%
            if current_user.id < result.id
              @user_id1, @user_id2 = current_user.id, result.id
            else
              @user_id1, @user_id2 = result.id, current_user.id
            end

            @room = Room.find_by(user_id1:@user_id1, user_id2:@user_id2)
            if @room == nil
          %>

            <td><%= button_to 'ルーム作成', rooms_create_path(user_id1:@user_id1, user_id2:@user_id2), method: :post, class:"roomMake_link" %></td>
          <% else %>
            <td><%= button_to 'ルーム入室', "/rooms/#{@room.id}", method: :get, class:"roomEntry_link" %></td>
          <% end %>
        <% else %>
          <td class="roomEmpty"> </td>
        <% end %>
        </tr>
      <% end %>

    <% end %>
  </tbody>
</table>

app/views/users/select.html.erb
<br><br>


<center>
  <table>
    <tbody>
      <tr>
        <td>
          <%= button_to "ユーザー情報編集", user_update1_path(), method: :get, class:"edit_info_btn" %>
        </td>

        <td>
          <%= button_to "PW編集", user_update2_path(), method: :get, class:"edit_pw_btn" %>
        </td>
      </tr>
    </tbody>
  </table>
</center>

app/views/users/show.html.erb
<div class="item-list">
  <center>
    <div class="myprofile">
      <%= render '/users/show_myprofile' %>
    </div>
  </center>

    <p>&emsp;</p>
  <center>
    <div class="followerlist">
      <%= render '/users/show_followerlist' %>
    </div>
  </center>
</div>