config/routes.rb
Rails.application.routes.draw do


  get 'users/edit1' => 'users#edit1', as: :user_update1
  get 'users/edit2' => 'users#edit2', as: :user_update2
  get 'users/select' => 'users#select'

  

  get '/' => 'users#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'comments/new'
  post 'comments/create'
  get 'comments/index'
  post 'comments/create', as:"comments"
  get 'rooms/create'
  #get 'rooms/destroy'
  resources :rooms

  post 'rooms/create'

  get 'friends/new'
  get 'friends/create'
  get 'friends/edit1'
  get 'friends/edit2'
  delete 'friends/destroy'
  namespace :admin do
    resources :users
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.htmls

  resources :users
  get 'search' => 'users#search'
  get "users/:id" =>'users#show'



  mount ActionCable.server => '/cable'
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :comments

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json

  # GET /rooms/1 or /rooms/1.json
  def show
    comments = Comment.where(room_id:@room.id, sender_id:current_user.id) + Comment.where(room_id:@room.id, receiver_id:current_user.id)
    @comments = comments.sort {|a, b| a[:created_at] <=> b[:created_at]}
    @current_user_id = current_user.id
  end

  # GET /rooms/new

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    user1 = User.find(room_params[:user_id1])
    user2 = User.find(room_params[:user_id2])

    if Room.find_by(user_id1:user1.id, user_id2:user2.id) == nil
      @room = Room.new(room_params)
      @room.save
      redirect_to "/rooms/#{@room.id}"
    else
      roomid = Room.find_by(user_id1:user1.id, user_id2:user2.id).id
      redirect_to "/rooms/#{roomid}"
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      if Room.exists?(params[:id])
        @room = Room.find(params[:id])
      else
        redirect_to users_path
      end
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.permit(:user_id1, :user_id2)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :userid1 %>
    <%= form.text_field :userid1 %>
  </div>

  <div class="field">
    <%= form.label :userid2 %>
    <%= form.text_field :userid2 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<body class="body">
  <%
    room1 = Room.find_by(user_id1:current_user.id)
    room2 = Room.find_by(user_id2:current_user.id)
    friend11, friend12, friend21, friend22 = nil, nil, nil, nil

    if room1 != nil
      friend11 = Friend.find_by(user_id:room1.user_id2, friend_id:room1.user_id1, allow:true)
      friend12 = Friend.find_by(user_id:room1.user_id1, friend_id:room1.user_id2, allow:true)
    elsif room2 != nil
      friend21 = Friend.find_by(user_id:room2.user_id2, friend_id:room2.user_id1, allow:true)
      friend22 = Friend.find_by(user_id:room2.user_id1, friend_id:room2.user_id2, allow:true)
    end

    if(room1 == nil && room2 == nil)
  %>
    <center><h2>申し訳ありません　このページは表示できません…  </h2></center>
    <center><%= link_to "トップへ戻る", users_path %></center>
  <% elsif (friend11 != nil && friend12 != nil) || (friend21 != nil && friend22 != nil) %>

  <%
    sender_id, receiver_id = @room.user_id1, @room.user_id2
    if sender_id != current_user.id
      sender_id, receiver_id = receiver_id, sender_id
    end
    senderid = User.find(sender_id).userid
    roomid = @room.id
    room_id = "comments" + roomid.to_s + "_" + @room.user_id1.to_s + "_" + @room.user_id2.to_s
  %>


  <div class="item-list">
    <center>
      <div class="">
        <div id="msg_box" class="msg_box" align="">
          <div id='<%= room_id%>'>
            <%= render @comments %>
          </div>
        </div>
      </div>
    </center>

    <center>
      <div class="">
        <%= form_with(model: Comment.new(), id:"form" ) do |form| %>
        <%= form.hidden_field :emotion, :value => 2 %>
        <%= form.hidden_field :expression, :value => 0 %>
          <table align="center">
            <%= form.hidden_field :senderid, :value => senderid, id:"form_senderid" %>
            <%= form.hidden_field :sender_id, :value => sender_id, id:"form_sender_id" %>
            <%= form.hidden_field :receiver_id, :value => receiver_id, id:"form_receiver_id" %>
            <%= form.hidden_field :room_id, :value => roomid, id:"form_room_id" %>
            <tr>
              <td colspan="8"><%= form.text_field :title, id:"comment_form_title", class: "comment_form_title", oninput:"check_btn()", data: { behavior: 'room_speaker'}, placeholder: "ここに件名を入力..." %></td>
            </tr>
            <tr>
              <td colspan="8"><%= form.text_area :long_content, id:"comment_form_long", class: "comment_form_long", oninput:"check_btn()", data: { behavior: 'room_speaker'}, placeholder: "ここに本文を入力..." %></td>
            </tr>
            <tr>
              <td align="center"><label><%= form.radio_button :expression, 0, id:"expression_0", class:"radio", onclick:"check_btn()", checked:true %><%= image_tag "expression_0.png", class:"radio_expression" %></label></td>
              <td align="center"><label><%= form.radio_button :expression, 1, id:"expression_1", class:"radio", onclick:"check_btn()" %><%= image_tag "expression_1.png", class:"radio_expression" %></label></td>
              <td align="center"><label><%= form.radio_button :expression, 2, id:"expression_2", class:"radio", onclick:"check_btn()" %><%= image_tag "expression_2.png", class:"radio_expression" %></label></td>
              <td align="center"><label><%= form.radio_button :expression, 3, id:"expression_3", class:"radio", onclick:"check_btn()" %><%= image_tag "expression_3.png", class:"radio_expression" %></label></td>
              <td><label><%= form.radio_button :emotion, 0, class:"radio" %><%= image_tag "emotion_0.png", class:"radio_emotion", id:"emotion_0", onclick:"check_radio_btn()" %></label></td>
              <td><label><%= form.radio_button :emotion, 1, class:"radio" %><%= image_tag "emotion_1.png", class:"radio_emotion", id:"emotion_1", onclick:"check_radio_btn()" %></label></td>
              <td><label><%= form.radio_button :emotion, 3, class:"radio" %><%= image_tag "emotion_3.png", class:"radio_emotion", id:"emotion_3", onclick:"check_radio_btn()" %></label></td>
              <td><label><%= form.radio_button :emotion, 4, class:"radio" %><%= image_tag "emotion_4.png", class:"radio_emotion", id:"emotion_4", onclick:"check_radio_btn()" %></label></td>
            </tr>
            <tr>
              <td colspan="7"><%= form.text_area :content, id:"comment_form", class: "comment_form", oninput:"check_btn()", data: { behavior: 'room_speaker'}, placeholder: "ここにメッセージを入力..." %></td>
              <td><%= image_submit_tag "submit.png", class:"submit_button", id:"submit_button", disabled:true%></td>
            </tr>
          </table>
      </div>
    </center>
  </div>
    <% end %>

  <% else %>
    <center><h2>申し訳ありません　このページは表示できません…  </h2></center>
    <center><%= link_to "トップへ戻る", users_path %></center>
  <% end %>
</body>



<script type="text/javascript">
  window.addEventListener('load', function() {
    document.getElementById('comment_form').focus();
  })

  function check_radio_btn(){
    var emotion_0 = document.getElementById('emotion_0');
    var emotion_1 = document.getElementById('emotion_1');
    var emotion_3 = document.getElementById('emotion_3');
    var emotion_4 = document.getElementById('emotion_4');
    if(emotion_0.checked){
      emotion_0.checked = false;
    }
  }


  function check_btn(){
    var comment_form = document.getElementById('comment_form').value;
    var comment_form_long = document.getElementById('comment_form_long').value;
    var comment_form_title = document.getElementById('comment_form_title').value;
    var expression_0 = document.getElementById('expression_0');
    var expression_1 = document.getElementById('expression_1');
    var expression_2 = document.getElementById('expression_2');
    var expression_3 = document.getElementById('expression_3');

    const submit_button = document.getElementById('submit_button');

    if(expression_0.checked){
      if(comment_form){
        submit_button.disabled = false;
      }
      else{
        submit_button.disabled = true;
      }
    }
    else if(expression_1.checked || expression_2.checked || expression_3.checked){
      if(comment_form_long && comment_form_title){
        submit_button.disabled = false;
      }
      else{
        submit_button.disabled = true;
      }
    }



  }
</script>